server {
    listen 80;
    index index.php index.html;
    root /var/www/public;


    # Serve arquivos estáticos do Vite (JS/CSS)
    location ^~ /build/ {
        alias /var/www/public/build/;
        access_log off;
        add_header Cache-Control "public, max-age=31536000, immutable";
        try_files $uri =404;
        types {
            text/javascript js;
            application/javascript mjs;
            text/css css;
        }
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~ /\.ht {
        deny all;
    }
}
